### ISSUE TITLE
Update analyzer protocol to use Language Server Protocol

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#3484]
Our current analyzer protocol does not match [Language Server Protocol](https://github.com/Microsoft/language-server-protocol). We should enable it.

- [x] Switch to JSON-based protocol
- [x] Switch to line/column identification
- [x] Switch to URI document identification (#3530)
- [x] Add LSP-compatible server (#3530) 
- [x] Update existing analyzer to defer to server (#3530)
- [x] Migrate normal completions to server (#3530)
- [x] Migrate special completions to server (#3798)
- [x] Migrate signature help to server (#3592)
- [ ] Migrate formatting to server
- [ ] Migrate refactoring to server (#4693)
- [x] Migrate hover to server (#3793)
- [x] Migrate find definition to server (#3803)

Additional items that are not currently implemented:
- [ ] Implement on type formatting (#4694)
- [ ] Implement type definition
- [ ] Implement code lens
- [ ] Implement code action
- [ ] Implement links
- [ ] Implement colours (i.e. dropdown next to colour literals)
